### ISSUE TITLE
Generate starter project into the developer's repository

### ISSUE THREAD

**Issue by Marcjazz** [spring-io/start.spring.io#1692] opened 2024-12-25 11:19 UTC
Spring Initializr should offer the possibility to connect to the developer's account, create and initialize the repository from the [start.sping.io](https://start.spring.io/) UI.

**Comment by snicoll** [comment] 2024-12-31 09:03
I suppose you mean create a repository from GitHub? Please clarify.

**Comment by Marcjazz** [comment] 2024-12-31 13:30
Yes,I'm suggesting to give developers the possibility to checkout the generated source code in a new GitHub repository instead of always downloading the compressed file.

**Comment by snicoll** [comment] 2024-12-31 14:09
Thanks. That's a duplicate of https://github.com/spring-io/initializr/issues/751

**Closed by snicoll** 2024-12-31 14:09 UTC
Labels: status: waiting-for-triage, status: feedback-provided
