### ISSUE TITLE
push generated project to the git repo

### ISSUE THREAD

**Issue by mulderbaba** [spring-io/start.spring.io#177] opened 2019-07-04 21:11 UTC
As an alternative to exploring or downloading the code of the generated project, it'd be an enhancement to provide a way to the user where they can push the code to their favorite (bitbucket, github, gitlab or whatever) git repository.

**Comment by wilkinsona** [comment] 2019-07-04 22:06
Thank you for the suggestion. I have edited its description to remove the assumption that a hypothetical user will be male.

**Comment by wilkinsona** [comment] 2019-07-04 22:09
This is a duplicate of https://github.com/spring-io/initializr/issues/63. We are considering an alternative in https://github.com/spring-io/initializr/issues/751.

**Closed by wilkinsona** 2019-07-04 22:09 UTC
