### ISSUE TITLE
Add support for Azure Spring Cloud

### ISSUE THREAD

**Issue by yiliuTo** [spring-io/start.spring.io#686] opened 2021-04-28 14:31 UTC
Hi there, the Azure Spring Integration team recently has published a bom of [com.azure.spring:azure-spring-cloud-dependencies;2.4.0](https://mvnrepository.com/artifact/com.azure.spring/azure-spring-cloud-dependencies) which will be maintained in the future together with another bom of [azure-spring-boot-bom](https://github.com/spring-io/start.spring.io/blob/main/start-site/src/main/resources/application.yml#L32), thus may I know if we could add this bom and its managed spring cloud libraries into start.spring.io?

The entries that we hope could be contained are:
 - azure-spring-cloud-starter-eventhubs-kafka
 - azure-spring-cloud-stream-binder-eventhubs
 - azure-spring-cloud-stream-binder-servicebus-queue
 - azure-spring-cloud-stream-binder-servicebus-topic
 - azure-spring-cloud-starter-storage-queue
 - azure-spring-cloud-starter-cache
 - spring-cloud-starter-azure-appconfiguration-config

If this proposal could be supported, we would like to provide all necessary information required by start.spring.io, like library description, sample link and so on.

**Comment by snicoll** [comment] 2021-04-30 06:16
> may I know if we could add this bom and its managed spring cloud libraries into start.spring.io?

Thanks for the suggestion but I am not sure I understand it fully. Do you mean adding that bom so that users can manually add more dependencies covered by "Azure Support" or do you mean adding new entries on the site so that users can select them. If you mean the later, the `entry-proposal` section had a checklist of things we would need to be able to answer that question. 

Based on the list that you've added and that I understand to be a list of new entries:

* `azure-spring-cloud-starter-eventhubs-kafka` could be added when Spring Cloud Stream, Kafka, and Azure Support are selected.
* We won't had binder as we prefer to offer either as smart combination, or references in `HELP.md`. If such reference is possible, we can discuss adding some logic for it.
* `azure-spring-cloud-starter-storage-queue`: start.spring.io already has a "Azure Storage" entry. Adding a "Azure Storage Queue" alongside to it will be confusing IMO so we would need more details.
* `azure-spring-cloud-starter-cache`: we don't offer cache libraries at the moment so adding an entry for this would be inconsistent. We could add the starter if "Cache" and "Azure Support" are selected though.
* `spring-cloud-starter-azure-appconfiguration-config`: I am a bit confused by the naming here. Why do we have "azure-spring-cloud-starter" and a single "spring-cloud-starter-azure" ? Are all of this part of Spring Cloud Azure or only this starter?

Please clarify what you had in mind and we can continue the discussion.

**Comment by spring-projects-issues** [comment] 2021-05-07 06:17
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by yiliuTo** [comment] 2021-05-07 07:43
Sorry for the late reply. 
### Clarification for entry proposal
> Do you mean adding that bom so that users can manually add more dependencies covered by "Azure Support" or do you mean adding new entries on the site so that users can select them.

Yes, what we hope is actually the latter one to add the listed entries on start.spring.io. Meanwhile, we also publish a [bom](https://repo1.maven.org/maven2/com/azure/spring/azure-spring-cloud-dependencies/2.4.0/azure-spring-cloud-dependencies-2.4.0.pom) managing those starters, so we hope the bom could be added as well. Thus when a user selects keywords mapping to our starter, let's take your suggestion as an example:

> azure-spring-cloud-starter-eventhubs-kafka could be added when Spring Cloud Stream, Kafka, and Azure Support are selected.

then the generated pom will contain
```
  <dependencies>
    <dependency>
      <groupId>com.azure.spring</groupId>
      <artifactId>azure-spring-cloud-starter-eventhubs-kafka</artifactId>
    </dependency>
  </dependencies>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.azure.spring</groupId>
        <artifactId>azure-spring-cloud-dependencies</artifactId>
        <version>${azure.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```
### Starter mapping
I have one concern that the package name `Azure Support` has already been [assigned](https://github.com/spring-io/start.spring.io/blob/b1ad9e7fdafce7775b2badabac5f496846cab659/start-site/src/main/resources/application.yml#L1400) to `azure-spring-boot-starter`, but now we have a series of starters for both azure spring boot and azure spring cloud, then that name may be not suitable. Is it possible to modify it from `Azure Support` to `Azure Spring Boot`? 

And for the suggestion: 

> azure-spring-cloud-starter-cache: we don't offer cache libraries at the moment so adding an entry for this would be inconsistent. We could add the starter if "Cache" and "Azure Support" are selected though.

> azure-spring-cloud-starter-eventhubs-kafka could be added when Spring Cloud Stream, Kafka, and Azure Support are selected. 

Due to azure-spring-boot-starter is not a spring cloud library, so to combine it with the cache starter or kafka starter may not be a good idea I think. We could discuss about how to find a solution.

Besides, I am a bit confused of how to select "Spring Cloud Stream, Kafka, and Azure Support" at the same time? Do you mean typing multiple keywords when searching for a package? Or when a user has already selected below packages, then `azure-spring-cloud-starter-eventhubs-kafka` will also be added into pom.xml automatically?
![image](https://user-images.githubusercontent.com/63028776/117415430-e509d680-af4a-11eb-9213-84e2a356f159.png)

For the concern 

> spring-cloud-starter-azure-appconfiguration-config: I am a bit confused by the naming here. Why do we have "azure-spring-cloud-starter" and a single "spring-cloud-starter-azure" ? Are all of this part of Spring Cloud Azure or only this starter?

We have a plan to modify its artifact id to be align with our other starter, so we decide not to add this starter this time.

For the concern
 
> start.spring.io already has a "Azure Storage" entry. Adding a "Azure Storage Queue" alongside to it will be confusing IMO so we would need more details.

[Azure Storage Queue](https://docs.microsoft.com/azure/storage/queues/storage-queues-introduction) is messaging service while [Azure Storage](https://docs.microsoft.com/azure/storage/common/storage-introduction) is for date storage.

### Binder

> We won't had binder as we prefer to offer either as smart combination, or references in HELP.md. If such reference is possible, we can discuss adding some logic for it.

- May I know what "smart combincation" mean here and how could I achieve it? 
- And as for HELP.MD, how should I provide some customized information about binders to start.spring.io? The info may contain the links of Maven, GitHub repo, sample, documentation.

### New proposal checklist

I will update the information required by that checklist soon in another comment.

**Comment by yiliuTo** [comment] 2021-05-08 06:55
The GitHub repo is at: https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring , there are 879 stars and 1k forks currently.

## Licence
MIT licence

## Issue Tracker URL
https://github.com/Azure/azure-sdk-for-java/issues

## Continuous integration
https://dev.azure.com/azure-sdk/public/_build?definitionId=1326&_a=summary

## Maven Central
- [azure-spring-cloud-starter-cache](https://mvnrepository.com/artifact/com.azure.spring/azure-spring-cloud-starter-cache)
- [azure-spring-cloud-starter-eventhubs-kafka](https://mvnrepository.com/artifact/com.azure.spring/azure-spring-cloud-starter-eventhubs-kafka)
- [azure-spring-cloud-starter-eventhubs](https://mvnrepository.com/artifact/com.azure.spring/azure-spring-cloud-starter-eventhubs)
- [azure-spring-cloud-starter-servicebus](https://mvnrepository.com/artifact/com.azure.spring/azure-spring-cloud-starter-servicebus)
- [azure-spring-cloud-starter-storage-queue](https://mvnrepository.com/artifact/com.azure.spring/azure-spring-cloud-starter-storage-queue)

## Configuration metadata
Implemented by adding spring-boot-configuration-processor in pom.xml.

## Version mappings
version 2.4.0 is compatible with Spring Cloud 2020.0.x, Spring Boot 2.4.x

## Links to additional resources

### Reference documentation:
- [azure-spring-cloud-starter-cache](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-cloud-starter-cache/README.md)
- [azure-spring-cloud-starter-eventhubs-kafka](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-cloud-starter-eventhubs-kafka/README.md)
- [azure-spring-cloud-starter-eventhubs](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-cloud-starter-eventhubs/README.md)
- [azure-spring-cloud-starter-servicebus](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-cloud-starter-servicebus/README.md)
- [azure-spring-cloud-starter-storage-queue](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-cloud-starter-storage-queue/README.md)
### Sample:
- [azure-spring-cloud-starter-cache](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples/azure-spring-cloud-sample-cache)
- [azure-spring-cloud-starter-eventhubs-kafka](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples/azure-spring-cloud-sample-eventhubs-kafka)
- [azure-spring-cloud-starter-eventhubs](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples/azure-spring-cloud-sample-messaging-eventhubs)
- [azure-spring-cloud-starter-servicebus](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples/azure-spring-cloud-sample-messaging-servicebus)
- [azure-spring-cloud-starter-storage-queue](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples/azure-spring-cloud-sample-storage-queue-operation)

**Comment by snicoll** [comment] 2021-05-17 08:07
> I have one concern that the package name Azure Support has already been assigned to azure-spring-boot-starter, but now we have a series of starters for both azure spring boot and azure spring cloud, then that name may be not suitable. Is it possible to modify it from Azure Support to Azure Spring Boot Support?

I am not keen to do that. I think the current arrangement between Azure Spring Boot and Spring Cloud Azure is quite confusing (we've had several meetings around that topic already). For what I've suggested, I think we need to keep a single entry that enables "Azure Support". An improvement could be that this entry configures both the Azure Spring Boot BOM and the Spring Cloud Azure BOM. we could also add some notes in `HELP.md` to guide users. 

> Due to azure-spring-boot-starter is not a spring cloud library, so to combine it with the cache starter or kafka starter may not be a good idea I think. We could discuss about how to find a solution.

I don't understand what the problem is. Our goal is to offer use cases and help users getting started quickly. When they select "Azure Support" on the site, they don't really care what's happening behind the scenes. It's our job to build a project that helps them get started.


> Besides, I am a bit confused of how to select "Spring Cloud Stream, Kafka, and Azure Support" at the same time? Do you mean typing multiple keywords when searching for a package? Or when a user has already selected below packages, then azure-spring-cloud-starter-eventhubs-kafka will also be added into pom.xml automatically?

The latter. If you look on start.spring.io right now, you won't find a "Spring Cloud Stream Kafka binder" (the core binder of Spring Cloud Stream). We won't add a dedicated entry for the azure specific one. Rather, users opt-in for selected technologies and we bring the most effective starter for them. If you want to use spring cloud stream with Kafka and Azure (those 3 dependencies, yes), then we can bring the starter. That's what I am suggesting in my inital reply.

If we added every possible combination, it would explode the number of entries and make the searcher quite hard to use.


> Azure Storage Queue is messaging service while Azure Storage is for data storage.

I think we need to take a step back and consider what a user would do on the site. If we'd offer "Azure Storage" and "Azure Storage Queue", how are you expecting users to understand which one they have to chose? I wouldn't. 



> May I know what "smart combincation" mean here and how could I achieve it?

This has been described several times previously: "Spring Cloud Stream" + a compatible tech (e.g. Kafka) + "Azure Support".

> And as for HELP.MD, how should I provide some customized information about binders to start.spring.io? The info may contain the links of Maven, GitHub repo, sample, documentation.

You don't have to worry to much about the how. What we need from you is to look at the use cases we want to achieve with Azure and what resources the user may need to learn more about them. 

I'd like us to switch focus from "adding entries" to "adding use cases". What can we do to help users get started with Azure? I want to improve the user experience so any help you can provide around that will be much welcome.

**Comment by spring-projects-issues** [comment] 2021-05-24 08:11
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by yiliuTo** [comment] 2021-05-26 01:51
Please hold this issue open, we are discussing the mentioned use cases internally, and will update here soon.

**Comment by snicoll** [comment] 2021-05-27 07:08
No worries @yiliuTo. If the bot closes it, we can reopen the issue once you have more feedback to share. Let me know if I can help.

**Comment by spring-projects-issues** [comment] 2021-06-02 06:42
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-06-09 06:40
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-06-09 06:40 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
