### ISSUE TITLE
JDK11 selected, but JDK17 generated

### ISSUE THREAD

**Issue by clnative** [spring-io/start.spring.io#1126] opened 2023-03-04 07:30 UTC
I just generated a new project with the following configuration:

![image](https://user-images.githubusercontent.com/97834051/222882309-1e05943b-e9b3-4894-8db6-4f5b2854b45d.png)

However, the `pom.xml` of the generated zip-file downloaded contains:

```
	<properties>
		<java.version>17</java.version>
	</properties>
```

So, it selects java compiler version 17, but I requested version 11.

**Comment by clnative** [comment] 2023-03-04 07:32
Configuration link: https://start.spring.io/#!type=maven-project&language=java&platformVersion=3.0.4&packaging=jar&jvmVersion=11&groupId=com.sap.ngpbug&artifactId=sshcrash&name=sshcrash&description=Demo%20project%20for%20Spring%20Boot&packageName=com.sap.ngpbug.sshcrash&dependencies=web

**Comment by bclozel** [comment] 2023-03-04 09:21
Closing as a duplicate of #1041 
Also see https://github.com/spring-io/start.spring.io/issues/1123#issuecomment-1451398722

**Closed by bclozel** 2023-03-04 09:21 UTC
Labels: status: waiting-for-triage
