### ISSUE TITLE
Invalid POM when "Description" contains an ampersand (&)

### ISSUE THREAD

**Issue by steveschnepp** [spring-io/start.spring.io#517] opened 2020-08-14 13:42 UTC
If you
1. go to https://start.spring.io 
1. choose `Maven Project`
1. enter `Demo project for Spring Boot & Others` in the _Description_ field

The generated POM is invalid XML, as it contains an unescaped ampersand.

    <description> Demo project for Spring Boot & Others </description>

The correct way would be:

    <description> Demo project for Spring Boot &amp; Others </description>

**Comment by snicoll** [comment] 2020-08-14 15:34
Thank you for the report.  This is a duplicate of https://github.com/spring-io/initializr/issues/1066.

**Closed by snicoll** 2020-08-14 15:34 UTC
Labels: status: waiting-for-triage
