### ISSUE TITLE
Upgrade spring-cloud-stream-test-support

### ISSUE THREAD

**Issue by jabrena** [spring-io/start.spring.io#567] opened 2020-11-12 08:55 UTC
Currently,

when a user add the dependency: `Cloud Stream`:

```
curl https://start.spring.io/starter.zip -d dependencies=cloud-stream \
           -d bootVersion=2.3.5.RELEASE \
           -o my-project.zip
```

The Web app, create a Java project with a `pom.xml` which add a old testing dependency:

```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-test-support</artifactId>
			<scope>test</scope>
		</dependency>
```

According with the documentation:
https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/current/reference/html/spring-cloud-stream.html#_testing

This is the new testing dependency  to use:

```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-stream</artifactId>
    <version>${spring.cloud.strea.version}</version>
    <type>test-jar</type>
    <scope>test</scope>
    <classifier>test-binder</classifier>
</dependency>
```

In the other hand, why it is not possible to add the `RabbitMQ` & `Kafka` Binders?

```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-binder-rabbit</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-binder-kafka</artifactId>
		</dependency>
```

Many thanks in advance

Juan Antonio

**Comment by snicoll** [comment] 2020-11-12 09:13
Thanks for the report, this is a duplicate of #385. 

> In the other hand, why it is not possible to add the RabbitMQ & Kafka Binders?

Please don't raise two completely separate topics in the same issue. You need to select either Rabbit or Kafka and we'll add the relevant binder automatically.

**Closed by snicoll** 2020-11-12 09:13 UTC
Labels: type: entry-upgrade

**Comment by jabrena** [comment] 2020-11-16 13:01
Thanks @snicoll
