### ISSUE TITLE
Generated project with Gradle+Kotlin+JPA does not build

### ISSUE THREAD

**Issue by der-ambi** [spring-io/start.spring.io#1547] opened 2024-08-08 08:27 UTC
I generated a demo project on https://start.spring.io with the following settings

<img width="1506" alt="image" src="https://github.com/user-attachments/assets/56f15e35-a7c5-4739-952d-0e8095446b67">

The resulting project does not build:
```shell
➜  demo ./gradlew build

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ambi/Projects/demo/build.gradle' line: 4

* What went wrong:
An exception occurred applying plugin request [id: 'org.hibernate.orm', version: '6.5.2.Final']
> Failed to apply plugin 'org.hibernate.orm'.
   > Could not create an instance of type org.hibernate.orm.tooling.gradle.HibernateOrmSpec.
      > Extension of type 'JavaPluginExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, VersionCatalogsExtension, SpringBootExtension, StandardDependencyManagementExtension, SourceSetContainer]

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 401ms
```

To fix it, I need to add to add a line `id 'java'`  to the `plugins` section of `build.gradle` so it reads like this
```groovy
plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.2'
	id 'io.spring.dependency-management' version '1.1.6'
	id 'org.hibernate.orm' version '6.5.2.Final'
	id 'org.graalvm.buildtools.native' version '0.10.2'
	id 'org.jetbrains.kotlin.plugin.jpa' version '1.9.24'
	id 'org.jetbrains.kotlin.jvm' version '1.9.24'
	id 'org.jetbrains.kotlin.plugin.spring' version '1.9.24'
}
```

**Comment by mhalbritter** [comment] 2024-08-08 09:57
Duplicate of https://github.com/spring-io/start.spring.io/issues/1078.

You can move the Hibernate plugin at the end of your `plugins` list, and the problem goes away.

**Closed** 2024-08-08 09:57 UTC
Labels: status: duplicate

**Comment by der-ambi** [comment] 2024-08-08 10:38
> You can move the Hibernate plugin at the end of your `plugins` list, and the problem goes away.

I don't think that this very helpful. It's not *my* plugins list, it's the one generated by start.spring.io.

Can't developers expect that the generated files work out of the box without having to adjust them?

The Hibernate issue linked in #1078 is also closed, so there will be no automatic fix at some point in time introduced by a new Hibernate version.

This particular issue is also not documented somewhere (I don't consider a closed issue as documentation), this brought me here.

If there is a dependency between _BuildCustomizer_s, maybe it makes sense to store them in the code and obey them so that the customizers are called in correct order?

**Comment by mhalbritter** [comment] 2024-08-08 10:41
> Can't developers expect that the generated files work out of the box without having to adjust them?

Of course. But the underlying bug is not in start.spring.io, but in the Hibernate plugin. It doesn't react to adding a plugin, but uses the list of applied plugins when it is applied, which is not [recommended](https://docs.gradle.org/current/userguide/implementing_gradle_plugins.html).

Also I don't think https://hibernate.atlassian.net/browse/HHH-15557 is closed. It's state is "Awaiting contribution".

**Comment by mhalbritter** [comment] 2024-08-08 10:43
I'm currently looking at our options to workaround that issue, but can't promise anything.

**Comment by mhalbritter** [comment] 2024-08-08 13:17
I've just opened and fixed https://github.com/spring-io/initializr/issues/1559, which makes sure that the language plugins (java, groovy and kotlin) are always on the top of the gradle plugin list. This already was the case for java and groovy, and I think it was an oversight that this didn't happen for Kotlin.

With that, the issue you reported is gone after it's deployed to production.
