### ISSUE TITLE
Upgrade to Oracle JDBC 19.6.0.0 (and groupId)

### ISSUE THREAD

**Issue by aalmiray** [spring-io/start.spring.io#430] opened 2020-04-24 11:58 UTC
The latest version of the Oracle JDBC drivers is `19.6.0.0`.
The groupId was updated in Feb 21st 2020 to `com.oracle.database.jdbc`.

**Comment by snicoll** [comment] 2020-04-24 12:04
Thanks but this project has no opinion whatsoever on that.

Duplicate of https://github.com/spring-projects/spring-boot/issues/20333

**Closed by snicoll** 2020-04-24 12:04 UTC
Labels: type: entry-upgrade

**Comment by snicoll** [comment] 2020-04-24 12:14
@wilkinsona also reminded me that we have an explicit mapping for the driver which is an oversight since Spring Boot is providing dependency management for it. I've created #431
