### ISSUE TITLE
Java version wrong with a specific setup

### ISSUE THREAD

**Issue by Pochyxi** [spring-io/start.spring.io#1115] opened 2023-02-11 21:11 UTC
Hello folks, I'm beginner, so I'm not sure that it is an issue, but I found a "strange" behaviour.

<img width="1718" alt="image" src="https://user-images.githubusercontent.com/104896667/218281129-22d0f59b-7479-45aa-84c1-33350f43e991.png">

<img width="1718" alt="image" src="https://user-images.githubusercontent.com/104896667/218281156-c6cefb12-27a9-48e5-b83a-355b4e882e4e.png">

With those two setups, it seems that the Java version isn't configurated correctly in `pom.xml` file. Even if I specified Java 11 or Java 8, I found this entry in the xml:

```xml
<properties>
	<java.version>17</java.version>
</properties>
```

Is it a bug or am I missing something?

Thanks a lot for your work! 👋

**Comment by bclozel** [comment] 2023-02-12 07:54
This is a duplicate of #1041
See the comments there for the rationale. Thanks!

**Closed** 2023-02-12 07:54 UTC
Labels: status: waiting-for-triage
