### ISSUE TITLE
(🎁) Disable invalid combinations of options

### ISSUE THREAD

**Issue by KotlinIsland** [spring-io/start.spring.io#1119] opened 2023-02-22 07:16 UTC
Such as:

- Kotlin (< 1.8)+ Java 19
- Spring 3 + Java 8/11

Otherwise different options are selected and the generated project is wrong.

This is a crosspost of https://github.com/spring-io/initializr/issues/1377, because I'm not sure where it was supposed to be raised.

Similar to #250 (Actually I think it's a duplicate of #250)

**Comment by bclozel** [comment] 2023-02-22 08:17
Yes, this is a duplicate of #250. Thanks for reaching out!

**Closed** 2023-02-22 08:17 UTC
Labels: status: duplicate
