### ISSUE TITLE
Support Github Connect and Push along with download option

### ISSUE THREAD

**Issue by aghorpade** [spring-io/start.spring.io#187] opened 2019-07-09 15:02 UTC
Hi All,

We have good feature to download zip folder of project which will be created on spring.start.io
I am looking a feature where Connect With github on UI so I can login and push this spring project template on my github repository.
![pushOnGithub](https://user-images.githubusercontent.com/5318345/60899758-f1e01500-a262-11e9-9431-544ef55df8fe.png)

**Comment by wilkinsona** [comment] 2019-07-09 15:15
Thanks for the suggestion. This is a duplicate of #177.

**Closed by wilkinsona** 2019-07-09 15:15 UTC
