### ISSUE TITLE
Update screenshot  to include a more recent GA version of Spring Boot

### ISSUE THREAD

**Issue by knlkshyp** [spring-io/start.spring.io#1242] opened 2023-07-10 10:14 UTC
At page https://github.com/spring-io/start.spring.io/blob/main/USING.adoc, the current screenshot shows Spring Boot version 2.4.0 and has not been updated since long.
<img width="1440" alt="start-spring-io-spring-version-old" src="https://github.com/spring-io/start.spring.io/assets/15921119/03c9f1ad-1fcb-4f83-90ce-6db9fd02ae26">

Atleast this should be updated to the current major version of Spring Boot i.e. 3.x.x

**Comment by CodeWithSouma** [comment] 2023-07-14 17:42
I want to fix this issue

**Comment by snicoll** [comment] 2023-07-14 17:56
Thanks @CodeWithSouma the issue is yours.

**Comment by snicoll** [comment] 2023-07-18 04:41
Closing in favor of PR #1249

**Closed by snicoll** 2023-07-18 04:41 UTC
Labels: type: documentation
