### ISSUE TITLE
Selecting Java 11 for versions >3.0.0 downloads a Java 17 version.

### ISSUE THREAD

**Issue by jmahicks** [spring-io/start.spring.io#1267] opened 2023-08-01 20:37 UTC
Good day,

I am trying to download 3.1.2 in Java 11, but I get the following error message after I change the version in pom.xml to "11" from "17", even after specifying "Java 11" on the page:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/springframework/boot/SpringApplication has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

It seems that even when specifying the version as Java 11, version 3.1.2 and 3.0.9 are compiled in Java 17.

```
$ grep "version>" pom.xml | grep -v SNAPSHOT
		<version>3.1.2</version>
		<java.version>17</java.version>

$ grep "version>" pom.xml | grep -v SNAPSHOT
		<version>3.0.9</version>
		<java.version>17</java.version>
```

Version 2.7.14 is in Java 11.

```
$ grep "version>" pom.xml | grep -v SNAPSHOT
		<version>2.7.14</version>
		<java.version>11</java.version>
```

Are versions >3.0.0 only compiled in Java 17? It would seem so because even the `build.gradle` file shows `sourceCompatibility = '17'`.

Can the Java version radio buttons be disabled if that version of Java is unsupported in the currently selected Spring Boot version?

**Comment by scottfrederick** [comment] 2023-08-01 20:46
> Are versions >3.0.0 only compiled in Java 17?

Yes. Spring Boot 3 [requires Java 17 at a minimum](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Release-Notes#java-17-baseline-and-java-19-support). 

> Can the Java version radio buttons be disabled if that version of Java is unsupported in the currently selected Spring Boot version?

This is a duplicate of #1041.

**Closed** 2023-08-02 06:49 UTC
Labels: status: waiting-for-triage
