### ISSUE TITLE
Allow multi-module creation with spring initalizer

### ISSUE THREAD

**Issue by fededonna** [spring-io/start.spring.io#721] opened 2021-06-16 17:40 UTC
Right now spring initializer just creates a project with srcs at the root level, this is not always true for all projects. Sometimes you want to create a project, let's say with a web layer and an api layer separated in 2 modules one having spring web dependencies and a dependency to api.
Thanks in advance.

**Comment by wilkinsona** [comment] 2021-06-16 18:24
Thanks for the suggestion. This is a duplicate of #159.

**Closed by wilkinsona** 2021-06-16 18:24 UTC
Labels: status: waiting-for-triage
