### ISSUE TITLE
UI shortcut response error

### ISSUE THREAD

**Issue by qq253498229** [spring-io/start.spring.io#104] opened 2019-04-28 08:44 UTC
First I added Lombok dependency, and then I want to add actuator dependency.
After I entered "actu" in the input box, two options appeared below. The second option was what I needed. When I pressed the down key to try to move the cursor to the second option, the cursor went back to the first one.
![image](https://user-images.githubusercontent.com/31200516/56861580-d63fcf00-69d4-11e9-8af8-dcc3a0cde3c9.png)

**Comment by wilkinsona** [comment] 2019-04-28 09:28
Thanks for the report. I cannot reproduce the behaviour that you have described in either Safari or Chrome on macOS. Can you please let us know which OS and browser you are using?

**Comment by qq253498229** [comment] 2019-04-28 09:30
System: MacOS 10.14.4
Chrome version : 73.0.3683.103

**Comment by snicoll** [comment] 2019-04-28 12:07
This happens because your cursor is in the area of the first entry. This is a known issue for which we already have a fix with a new version of the UI we're working on. It hasn't been rolled out yet. 

I know this is annoying but moving the cursor away should fix it in the meantime.

cc @oodamien

**Comment by wilkinsona** [comment] 2019-04-28 13:08
> but moving the cursor away should fix it in the meantime.

Alternatively, you can just press return once you've used the arrow keys to highlight a particular dependency rather than returning to the mouse.

**Comment by oodamien** [comment] 2019-09-02 14:35
Fixed with the react version.

**Closed by oodamien** 2019-09-02 14:35 UTC
Labels: type: bug
