### ISSUE TITLE
When Spring Boot 3.0+ Java Version must be >= 17

### ISSUE THREAD

**Issue by danvega** [spring-io/start.spring.io#1121] opened 2023-02-27 18:39 UTC
I think it would be nice to disable Java 8 + 11 When Spring Boot 3.0+ is selected. 

Looking further down the road each major version of Spring Boot will have a baseline Java version associated with that. We could store those settings somewhere and check to see what version of Spring Boot is being selected and what version of Java should be disabled. 

I don't know enough about how the starter works but I will dig around and If I can figure this out I will send a PR.

**Comment by mbhave** [comment] 2023-02-27 18:45
This is a duplicate of https://github.com/spring-io/start.spring.io/issues/1041. See [this comment](https://github.com/spring-io/start.spring.io/issues/1041#issuecomment-1329456271) to see why it currently can't be disable. I'll close this issue as a duplicate but feel free to reopen if you had something else in mind.

**Closed by mbhave** 2023-02-27 18:45 UTC
Labels: status: waiting-for-triage
